### ISSUE TITLE
Access to the path "/home/AMP/.ampdata/instances" is denied.

### ISSUE THREAD

**Issue by MitchTalmadge** [CubeCoders/dockerfiles#2]
I am having trouble getting the image to work. It may be my fault. Here's the logs and my docker-compose.yml file:

```
root@cloud:/opt/minecraft# docker-compose up
WARNING: The V variable is not set. Defaulting to a blank string.
Recreating minecraft_amp_1 ... done
Attaching to minecraft_amp_1
amp_1  | [Info] AMP Instance Manager v1.7.1.0 built 04/01/2019 13:20
amp_1  | [Info] Release spec: Release - built by CUBECODERS/BuildBot on CCL-DEV
amp_1  | [Warning] AMP Service port ranges have not been specified, using any available...
amp_1  | [Warning] Application Service port ranges have not been specified, using any available...
amp_1  | [Error] Failed to unpack AMP.
amp_1  | [Error] Access to the path "/home/AMP/.ampdata/instances" is denied.
amp_1  | [Error]   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <3574b7750bbd4f3481d1561b74d01b33>:0
amp_1  |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <3574b7750bbd4f3481d1561b74d01b33>:0
amp_1  |   at System.IO.DirectoryInfo.Create () [0x00000] in <3574b7750bbd4f3481d1561b74d01b33>:0
amp_1  |   at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:Create ()
amp_1  |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00036] in <3574b7750bbd4f3481d1561b74d01b33>:0
amp_1  |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <3574b7750bbd4f3481d1561b74d01b33>:0
amp_1  |   at InstanceManagerPlugin.LocalInstanceManager+<DownloadAndUnpack>d__127.MoveNext () [0x00039] in <d3032b8621174092948bb924dba44f75>:0
amp_1  | [Info] Instance creation failed. The core archive failed to download or unpack
amp_1  | -su: ampinstmgr view ADS true: No such file or directory
minecraft_amp_1 exited with code 0
```

```
version: "3.7"
services:
  amp:
    image: cubecoders/amp:latest
    ports:
      - 25565:25565
      - 25566:8080
    volumes:
      - /var/opt/minecraft/amp:/data
    environment:
      - "AMPUSER=admin"
      - "AMPPASSWORD=notmyrealpassword"
```

Do you have any ideas? It seems to have less problems when I don't use a volume.
