### ISSUE TITLE
open terminal failed: not a terminal

### ISSUE THREAD

**Issue by mueslo** [CubeCoders/dockerfiles#4]
This is on cubecoders/amp:latest docker.

On first startup, the web interface loaded fine. I then set everything up, it told me it needed to restart.

Since then I get:
`amp_1     | [Info] AMP Instance Manager v1.9.5.2 built 30/01/2020 16:29
amp_1     | [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
amp_1     | [Info] An ADS instance has already been created! Starting that instead of re-running quickstart...
amp_1     | [Info] Starting Instance: 'ADS01'
amp_1     | [Info] Waiting for AMP instance to start...
amp_1     | [Notice] AMP instance ADS01 is now running.
amp_1     | [Info] You can browse to this instance at http://172.18.0.3:8080/
amp_1     | [Info] Instance started in new session. Run 'ampinstmgr View ADS01' to view this instances console.
amp_1     | [Info] AMP Instance Manager v1.9.5.2 built 30/01/2020 16:29
amp_1     | [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
amp_1     | open terminal failed: not a terminal
gaming_amp_1 exited with code 0 `

**Comment by peterwilli** [comment]
I have the same problem.

**Comment by peterwilli** [comment]
@mueslo I found the solution!
You have to add tty and stdin_open to your docker-compose file.

```
version: "3.7"
services:
  amp:
    image: cubecoders/amp:latest
    stdin_open: true
    tty: true
    ports:
      - 0.0.0.0:25565:25565
      - 0.0.0.0:25566:8080
    volumes:
      - ./amp_data:/data
```
